### ISSUE TITLE
Unable to create custom wondercard eggs

### ISSUE THREAD

**Issue by br45entei** [suloku/wc-tool#1]
![inject rom egg script nullpointerexception](https://cloud.githubusercontent.com/assets/4844374/23007458/707304cc-f3ce-11e6-8b0d-d7b892b9699e.png)
I am unsure if this project is still alive, but it has allowed me to get official wondercard events so that I can go catch legendary pokemon the 'legitimate' way! However, whenever I try to make a custom wondercard, the "Inject" button results in a null pointer exception. Here's hoping this is a simple fix! Thank you guys so much for such a wonderful tool.

P.S. I am using Windows 7 x64(using classic theme), and I even tried re-running the application with administrative privilages.

**Comment by suloku** [comment]
The project isn't dead, I just haven't had the time for updates and bugfixing.
This is a known issue: you are supposed to pre-load a wondercard file before using the inject script buttons.
The misslead comes from me forgetting to disable those buttons when no wc is loaded. On next update an empty wc file will be loaded by default, so wc can be created from scratch without the beed to load one.

**Comment by br45entei** [comment]
Ah, so how where do I get a wondercard file from, if what I'm wanting to do
is create one? I completely understand that you have to spend your time on
other life activities, I myself have been pretty busy working on other
things than my hobbies. Thank you for the reply!

P.S. If possible, it would make things a whole lot easier on me as far as
converting and loading save files back to my physical cart if your program
could additionally save/load directly to/from .xps, as I use an action
replay GBX to read and write directly to my original GBA. I don't have a DS
or a flash card that I can use, so I have to convert from the Action
replay's .xps file to an .sps, then from that I load into VBA-M, then I
load the game and rom up, save the game using the start menu, then find the
.sav file so I can use that for your program. Then, once I've used your
program, I load the exported .sav back into VBA-M, save again, export using
the VBA-M's "Export -> Gameshark snapshot" which gives me back a .sps, then
I have to open another program called "Circo's Pokemon Maker"(which I have
to run as administrator, otherwise it fails to start) and then do "File ->
Convert -> SPS to XPS" and THEN I can take that .xps and write it to my gba
via the action replay software on my older XP machine(since the action
replay drivers only work on a 32 bit system, and my main pc is a newer x64
machine). I was almost ready to give up on the conversion process back to
my gba before I remembered that I had downloaded "Circo's Pokemon Maker"
and that it had a convert option of some kind, and I got lucky that it was
exactly what I needed. Thank you anyway for the awesome program, this has
finally allowed me to experience a taste of what the legendary mystery gift
and events were made out to be!



*--Brian_Entei*

**Comment by suloku** [comment]
You can find all the official wondercards we collected in the binary release file, amongst some useful modified ones: https://github.com/suloku/wc-tool/releases

About XPS: I've just tried Ciro's Pokemon Maker conversion and xps and sps files are exactly the same. Can you upload a sps and xps file that you know work after converting?
It seems creating a proper sps/xps file needs some data that comes from the rom so the header can be created, so in fact the best converter is using the emulator.
I would suggest installing a virtual machine in your main computer with a 32bit sytem, that would solve the pc changing issue at least: http://www.virtualbox.org/

**Comment by br45entei** [comment]
This one is 129 kb, whereas the original is only 65kb. Any idea why one is
bigger, or is that just because the modified one contains more data? 

The GBA Pokémon save files are 128 kB, if the ones your AR device produce are 64kB is because it's only dumping half the savegame. Most flashcard back in the day (and now) used 64kB SRAM, so that's why almost all emulators work with the 64kB file. The pokémon gba games actually only use half the save file (the other half is used for backup purposes in case the main save corrupts), so there's really no impact in only using 64kB. What's surprises me is that your AR device allows you to use the 129kB file (the extra kB is the header data for de xps/sps file) but makes 64kB dumps.

Then sps and xps are just the same, so just rename.


About your other question: the wondercard scripts check for 2 flags and for the item in the bag. If any of the 3 is set, you can't trigger the event. Try removing the ticket with a save editor, as you said you may have cheated it in, but you need the item + the flags activated.
I don't know the game so much to answer about the girl in staleport.

**Comment by br45entei** [comment]
Ah, upon re-reading the forums, I indeed must have cheated on my emerald
save game before hand, according to your post at
https://projectpokemon.org/forums/forums/topic/39184-gen-iii-mystery-gift-tool-nintendo-events-wondercards-e-trainer-cards-and-e-berry-editor-and-more/?do=findComment&comment=204800
(specifically point #3 ...) so I'll be working on a "legitimate" run of my
emerald game later on in order to properly use the wondercards. Thank you
so much for explaining everything and all the hard work that you guys have
been putting into this!



*--Brian_Entei*

**Comment by br45entei** [comment]
Ah, I didn't realize that replying to the e-mail posted to here, I'll go ahead and close this issue since you've stated that you're already working on fixing the NPE when no wondercard file is imported :+1:

Now that I am more familiar with the different save game file formats, it's no big deal if a converter from sav to xps isn't added, but it would be incredibly useful if it were(or if xps were simply accepted and optionally saved when using the program)! Thanks again!

**Comment by suloku** [comment]
I'll state it once more for anyone else reading this: xps is not possible without ROM information, as it uses the rom header to prevent restoring to a different cart of origin (I don't really know, but I don't see any other usage).

I **may** add support to LOAD xps/sps, but saving as XPS is better done with VBA.

**Comment by br45entei** [comment]
Ah, my mistake, thank you for the clarification.
